import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronDown, ChevronUp, Flame, Eye, BarChart3, CheckCircle2, ArrowRight } from "lucide-react";
import { DataStatus, ConflictNotice } from "@/components/market/DataStatus";
import { ScoreRing } from "@/components/market/ScoreMeter";
import { Sparkline } from "@/components/market/Sparkline";
import { BriefingSkeleton, EmptyState, ErrorState } from "@/components/market/states";
import { formatMoney, formatPct } from "@/lib/market/market-service";
import { useActiveMarket } from "@/lib/market/use-active-market";
import { useSession } from "@/hooks/useSession";

export const Route = createFileRoute("/_authenticated/overview")({ component: Overview });

function Overview() {
 const { briefing, symbols } = useActiveMarket(); const { user } = useSession();
 if (!symbols.length) return <EmptyState title="Your market starts with what matters to you." body="Add your first stock and DELTA will begin remembering what you saw." action={<Link to="/watchlists" className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">+ Add your first stock</Link>}/>;
 if (briefing.isLoading) return <BriefingSkeleton/>; if (briefing.isError) return <ErrorState onRetry={()=>briefing.refetch()}/>; const b=briefing.data!;
 const first=user?.user_metadata?.full_name?.split(" ")[0]||user?.email?.split("@")[0]||"there";
 const attention=b.quotes.filter(q=>q.classification==="attention"); const normal=b.quotes.filter(q=>q.classification==="normal"||q.classification==="noise");
 return <div className="space-y-10 animate-in fade-in duration-500">
  <section className="flex flex-col gap-5 border-b border-border/60 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-muted-foreground">Good morning, {first} 👋</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight sm:text-5xl">Your market changed in <span className="text-primary">{b.counts.attention+b.counts.worthKnowing}</span> meaningful ways.</h1><p className="mt-3 text-muted-foreground">You were away for {b.awayLabel}. We filtered through the noise so you don&apos;t have to.</p><p className="mt-4 text-xs text-muted-foreground">Last checked · {new Date(b.lastCheckedAt).toLocaleString()}</p></div><DataStatus freshness={b.freshness}/></section>
  <ConflictNotice freshness={b.freshness}/>
  <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-muted-foreground">Attention summary</p><h2 className="mt-2 text-xl font-semibold">Your attention, protected.</h2></div><span className="rounded-full border border-primary/20 bg-primary/8 px-3 py-1 text-xs text-primary">Attention Load: {b.attentionLoad.toUpperCase()}</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Flame} label="Needs attention" value={b.counts.attention}/><Summary icon={Eye} label="Worth knowing" value={b.counts.worthKnowing}/><Summary icon={BarChart3} label="Normal movement" value={b.counts.normal}/><Summary icon={CheckCircle2} label="Filtered as noise" value={b.counts.noise}/></div><p className="mt-3 text-sm text-muted-foreground">Only {b.counts.attention} thing{b.counts.attention===1?"":"s"} currently deserve your attention.</p></section>
  <section>{attention.length>0?<><div className="mb-4"><h2 className="text-2xl font-semibold">Needs your attention</h2><p className="mt-1 text-sm text-muted-foreground">These changes were unusual or significant compared to what you last saw.</p></div><div className="space-y-4">{attention.map(q=><AttentionCard key={q.symbol} q={q}/>)}</div></>:<EmptyState title="Quiet market." body="Nothing needs your attention right now."/>}</section>
  {b.patterns[0] && <section className="panel overflow-hidden p-6"><p className="text-xs uppercase tracking-[.22em] text-muted-foreground">A pattern emerged</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_auto]"><div><h2 className="text-2xl font-semibold">📉 {b.patterns[0].headline}</h2><div className="mt-5 grid max-w-xl gap-2 sm:grid-cols-2">{b.patterns[0].members.map(m=><div key={m.symbol} className="flex justify-between rounded-lg bg-secondary/40 px-3 py-2 text-sm"><span>{m.name}</span><span className="text-down">{formatPct(m.pct)}</span></div>)}</div><p className="mt-4 text-sm text-muted-foreground">{b.patterns[0].description}</p><Link to="/insights" className="mt-5 inline-flex items-center gap-1 text-sm text-primary">Explore pattern <ArrowRight className="size-4"/></Link></div><ScoreRing score={b.patterns[0].strength} label="Pattern strength"/></div></section>}
  <section className="border-t border-border/60 pt-8"><h2 className="text-xl font-semibold">✓ You&apos;re caught up.</h2><p className="mt-2 text-sm text-muted-foreground">Nothing else in your watchlist changed enough to deserve your attention.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{normal.slice(0,4).map(q=><div key={q.symbol} className="flex items-center justify-between rounded-xl bg-secondary/35 px-4 py-3"><span className="text-sm">{q.name}</span><span className={q.sinceLastSeenPct<0?"text-down text-sm":"text-up text-sm"}>{formatPct(q.sinceLastSeenPct)}</span></div>)}</div></section>
 </div>
}
function Summary({icon:Icon,label,value}:{icon:any,label:string,value:number}){return <div className="rounded-xl border border-border/60 bg-card/55 p-5"><Icon className="size-4 text-primary"/><p className="mt-5 text-3xl font-semibold mono-nums">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></div>}
function AttentionCard({q}:{q:any}){const [open,setOpen]=useState(false); return <article className="panel p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-3"><div><p className="font-semibold">{q.name}</p><p className="mt-1 text-xs text-muted-foreground">{q.symbol}</p></div><span className="rounded-full bg-down/10 px-2.5 py-1 text-[10px] font-semibold tracking-wider text-down">UNUSUAL MOVEMENT</span></div><div className="mt-6 flex flex-wrap items-end gap-5"><div><p className="text-3xl font-semibold mono-nums">{formatMoney(q.price,q.currency)}</p><p className="mt-1 text-sm text-down">↓ {Math.abs(q.sinceLastSeenPct).toFixed(1)}% since you last checked</p></div><Sparkline points={q.spark} direction={q.sinceLastSeenPct<0?"down":"up"} width={160} height={48}/></div><p className="mt-5 max-w-xl text-sm text-muted-foreground">This movement is {q.volatilityMultiple.toFixed(1)}× higher than its recent normal volatility.</p><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><Metric label="Price when you last checked" value={formatMoney(q.lastSeenPrice,q.currency)}/><Metric label="Current price" value={formatMoney(q.price,q.currency)}/><Metric label="Difference" value={formatMoney(q.price-q.lastSeenPrice,q.currency)}/></div><button onClick={()=>setOpen(!open)} className="mt-6 flex items-center gap-1 text-sm text-primary">Why am I seeing this? {open?<ChevronUp className="size-4"/>:<ChevronDown className="size-4"/>}</button>{open&&<ul className="mt-4 space-y-2 text-sm text-muted-foreground">{q.reasons.map((r:string)=><li key={r}>✓ {r}</li>)}</ul>}</div><ScoreRing score={q.scores.total} size={88} label="Meaningfulness Score"/></div></article>}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-lg bg-secondary/45 p-3"><p className="text-muted-foreground">{label}</p><p className="mt-1 font-medium mono-nums">{value}</p></div>}
